runtime: python312
instance_class: F2
env_variables:
  PROJECT_ID: "プロジェクトID"
  LOCATION: "us-central1"
  VOICEVOX_API_KEY: "VOiCEVOXのAPIキー"

handlers:
- url: /select-main-theme
  script: auto
- url: /generate-story-parent
  script: auto
- url: /generate-story-child
  script: auto
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /.*
  static_files: static/\1
  upload: static/.*
